In [2]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/VM/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/VM/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/VM/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/VM/anaconda\\Library\\in

In [3]:
#create array
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#find mem size of array
mat = np.zeros((10, 10))
print(mat.itemsize, mat.size * mat.itemsize)

8 800


In [2]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

In [7]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#reverse
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
#create matrix from 0 - 9
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#find index of non-zero in arr
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4]),)


In [18]:
#create unit matrix
mat = np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#create random mat
mat = np.random.random((3,3,3))
print(mat)

[[[0.85680189 0.93508368 0.8959415 ]
  [0.24653787 0.94835934 0.69177833]
  [0.24233547 0.33559867 0.28535895]]

 [[0.64475389 0.51752899 0.86378392]
  [0.67244922 0.15800762 0.51936651]
  [0.60188439 0.57464609 0.91564454]]

 [[0.31744973 0.39335926 0.40610006]
  [0.11940774 0.50717243 0.61121465]
  [0.74617101 0.8995041  0.66558181]]]


In [22]:
#find max min of arr
arr = np.random.random((10, 10))
print(arr.max(), arr.min())

0.9931466023750247 0.003570977419905863


In [24]:
#create random arr and get average
arr = np.random.random(30)
print(arr.mean())

0.5004422877950935


In [27]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
#for arr, fill boarder with 0
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print(3 * 0.1)

nan
False
nan
False
0.30000000000000004


In [39]:
Z = np.diag(1+np.arange(4), k = -1)

In [44]:
#chess board
Z = np.zeros((8,8))
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1

In [54]:
#normalization to 5*5 mat
mat = np.arange(25).reshape(5,5)
mat = (mat - mat.min()) / (mat.max() - mat.min())
print(mat)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


In [49]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [47]:
print(Z)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

In [56]:
#define new type RGB
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)
                 ])
color

/Users/user/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [59]:
#cross prduct
Z = np.dot(np.ones((5,3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [61]:
#negate arr
Z = np.arange(10)
Z[(3 < Z) & (Z <= 8)] *= -1 
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [62]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [66]:
Z = np.arange(5)
print(Z**Z)
print(Z <- Z)


[  1   1   4  27 256]
[False False False False False]


In [75]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/user/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/user/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [80]:
#cut to float number
Z = np.random.uniform(-10, 10, 10)
cZ = np.ceil(np.abs(Z))
print(cZ)
print(np.copysign(cZ,Z))

[10.  4.  1.  7.  4.  5.  9.  9.  2.  2.]
[-10.   4.  -1.  -7.  -4.  -5.  -9.   9.   2.   2.]


In [83]:
#find comman values in two array
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[0 1 2 6 8]


In [12]:
#how to calculate (A+B)\*(-A/2) without copy values
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A, B, out = B)
np.divide(A,2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = B)

[-0.5 -0.5 -0.5] [3. 3. 3.]


array([-1.5, -1.5, -1.5])

In [20]:
#define 5 ways to extract integer part of random array
A = np.random.uniform(0,10,10) 
print(A - A%1)#1
print(np.floor(A))
print(np.ceil(A) - 1)
print(A.astype(int))
print(np.trunc(A))

[4. 7. 0. 1. 7. 8. 0. 5. 1. 4.]
[4. 7. 0. 1. 7. 8. 0. 5. 1. 4.]
[4. 7. 0. 1. 7. 8. 0. 5. 1. 4.]
[4 7 0 1 7 8 0 5 1 4]
[4. 7. 0. 1. 7. 8. 0. 5. 1. 4.]


In [23]:
#create 5*5 mat, range from 0 ~ 4
Z = np.zeros((5,5))
Z += np.arange(5)

In [26]:
def generateTen():
    for x in range(10):
        yield x

Z = np.fromiter(generateTen(), dtype=float, count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [27]:
#create random array, range from 0 ~ 1 exclusively
Z = np.linspace(0,1,11,endpoint=False)
print(Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
#create and sort random array
Z = np.random.random(10)
Z.sort()
print(Z)

[0.67416856 1.6796174  1.84613574 2.96057948 3.02231234 5.17366234
 5.5656327  6.58683274 8.86183581 9.1024311 ]
